openapi: "3.0.1"
info:
  title: "Financial Statements API"
  version: "v1"
servers:
  - url: "https://api.xero.com/finance.xro/1.0"
    description: "Production URL"
paths:
  /FinancialStatements/BalanceSheet:
    get:
      security:
        - OAuth2:
            - "finance.statements.read"
      tags:
        - "BalanceSheet"
      summary: "Get Balance Sheet report"
      description: "The Balance Sheet report is a standard financial report which describes the financial position of an organisation at a point in time."
      parameters:
        - name: "Xero-Tenant-Id"
          in: "header"
          description: "Xero Organisation Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "Xero-User-Id"
          in: "header"
          description: "Xero User Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "balanceDate"
          in: "query"
          description: "Specifies the date for balance sheet report.\r\n\r\nFormat yyyy-MM-dd. If no parameter is provided, the current date will be used."
          schema:
            type: "string"
          example: "2020-06-30"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceSheetResponse"
              example:
                balanceDate: "2021-05-12"
                asset:
                  accountTypes:
                    - accountType: "INVENTORY"
                      accounts:
                        - code: "630"
                          accountID: "abcdeabc-80bb-47f5-9418-d1fc2241b838"
                          name: "Inventory"
                          reportingCode: "ASS.CUR.INY"
                          total: 3
                      total: 3
                    - accountType: "CURRENT"
                      accounts:
                        - code: "610"
                          accountID: "abcdeabc-b4d1-45a5-82f7-19deda692a31"
                          name: "Accounts Receivable"
                          reportingCode: "ASS.CUR.REC.TRA"
                          total: 100
                      total: 100
                    - accountType: "BANK"
                      accounts:
                        - accountID: "abcdeabc-3a6d-4c53-ba82-ea1c92d02ef4"
                          name: "Buz Acc"
                          reportingCode: "ASS"
                          total: -42.3
                      total: -42.3
                  total: 60.7
                liability:
                  accountTypes:
                    - accountType: "CURRLIAB"
                      accounts:
                        - code: "820"
                          accountID: "abcdeabc-40f7-49f1-ad89-1930c1366e5b"
                          name: "GST"
                          reportingCode: "LIA.CUR.TAX.GST"
                          total: 1.59
                        - code: "860"
                          accountID: "abcdeabc-2877-4c00-be7d-475b1ded30d7"
                          name: "Rounding"
                          reportingCode: "LIA.CUR"
                          total: -0.1
                        - code: "800"
                          accountID: "abcdeabc-80ba-4b58-8d72-f8e9ca0f2f00"
                          name: "Accounts Payable"
                          reportingCode: "LIA.CUR.PAY.TRA"
                          total: 44.4
                      total: 45.89
                  total: 45.89
                equity:
                  accountTypes:
                    - accountType: "EQUITY"
                      accounts:
                        - accountID: "00000000-0000-0000-0000-000000000000"
                          name: "Current Year Earnings"
                          total: 14.81
                      total: 14.81
                  total: 14.81
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "invalid-request"
                title: "InvalidRequest"
                status: 400
                detail: "Organisation xxx does not exist"
        503:
          description: "Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "service-unavailable"
                title: "ServiceUnavailable"
                status: 503
                detail: "Cannot process org xxx at this time. Apologies for inconvenience."
  /FinancialStatements/Cashflow:
    get:
      security:
        - OAuth2:
            - "finance.statements.read"
      tags:
        - "Cashflow"
      summary: "Get Cash flow report"
      description: "The Statement of Cash flows - direct method, provides the year to date changes in operating, financing and investing activities for an organisation."
      parameters:
        - name: "Xero-Tenant-Id"
          in: "header"
          description: "Xero Organisation Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "Xero-User-Id"
          in: "header"
          description: "Xero User Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "startDate"
          in: "query"
          description: "Date e.g. yyyy-MM-dd\r\n\r\nSpecifies the start date for cash flow report.\r\n\r\nIf no parameter is provided, the date of 12 months before the end date will be used."
          schema:
            type: "string"
        - name: "endDate"
          in: "query"
          description: "Date e.g. yyyy-MM-dd\r\n\r\nSpecifies the end date for cash flow report.\r\n\r\nIf no parameter is provided, the current date will be used."
          schema:
            type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CashflowResponse"
              example:
                startDate: "2018-07-01"
                endDate: "2019-06-30"
                cashBalance:
                  openingCashBalance: 5000
                  closingCashBalance: -50000
                  netCashMovement: -55000
                cashflowActivities:
                  - name: "Operating Activities"
                    total: -41000
                    cashflowTypes:
                      - name: "Receipts from customers"
                        total: 34000
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "REVENUE"
                            accountClass: "REVENUE"
                            code: "455"
                            name: "Cellar Door - Till Variance"
                            reportingCode: "EXP"
                            total: -1000
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "CURRENT"
                            accountClass: "ASSET"
                            code: "123"
                            name: "Loan - Darleen's"
                            reportingCode: "ASS"
                            total: 35000
                      - name: "Payments to suppliers and employees"
                        total: -75000
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "CURRENT"
                            accountClass: "ASSET"
                            code: "123"
                            name: "Loan - Darleen's"
                            reportingCode: "ASS"
                            total: -75000
                  - name: "Investing Activities"
                    total: -35000
                    cashflowTypes:
                      - name: "Payment for property, plant and equipment"
                        total: -36000
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "FIXED"
                            accountClass: "ASSET"
                            code: "138"
                            name: "Motor Vehicles at Cost"
                            reportingCode: "ASS"
                            total: -1000
                          - accountId: "abcdefab-5353-9d4b-7cad-51b2c2a2754a"
                            accountType: "FIXED"
                            accountClass: "ASSET"
                            code: "140"
                            name: "Equipment at cost"
                            reportingCode: "ASS"
                            total: -35000
                      - name: "Proceeds from sale of property, plant and equipment"
                        total: 1000
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "FIXED"
                            accountClass: "ASSET"
                            code: "138"
                            name: "Motor Vehicles at Cost"
                            reportingCode: "ASS"
                            total: 1000
                          - accountId: "abcdefab-5353-9d4b-7cad-51b2c2a2754a"
                            accountType: "FIXED"
                            accountClass: "ASSET"
                            code: "140"
                            name: "Equipment at cost"
                            reportingCode: "ASS"
                            total: 0
                  - name: "Financing Activities"
                    total: -14000
                    cashflowTypes:
                      - name: "Proceeds from borrowings"
                        total: 1000.5
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "TERMLIAB"
                            accountClass: "LIABILITY"
                            code: "244"
                            name: "Loan - Shellcoll Distribution 2019"
                            reportingCode: "LIA.CUR.LOA"
                            total: 1000.5
                      - name: "Repayment of borrowings"
                        total: -15000.5
                        accounts:
                          - accountId: "abcdefab-4d1e-4d1a-9e4c-68b2c2a278e2"
                            accountType: "TERMLIAB"
                            accountClass: "LIABILITY"
                            code: "244"
                            name: "Loan - Shellcoll Distribution 2019"
                            reportingCode: "LIA.CUR.LOA"
                            total: -15000.5
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "invalid-request"
                title: "InvalidRequest"
                status: 400
                detail: "Organisation xxx does not exist"
        503:
          description: "Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "service-unavailable"
                title: "ServiceUnavailable"
                status: 503
                detail: "Cannot process org xxx at this time. Apologies for inconvenience."
  /FinancialStatements/ProfitAndLoss:
    get:
      security:
        - OAuth2:
            - "finance.statements.read"
      tags:
        - "ProfitAndLoss"
      summary: "Get Profit & Loss report"
      description: "The Profit & Loss statement is a standard financial report providing detailed year to date revenue and expense detail for an organisation."
      parameters:
        - name: "Xero-Tenant-Id"
          in: "header"
          description: "Xero Organisation Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "Xero-User-Id"
          in: "header"
          description: "Xero User Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "startDate"
          in: "query"
          description: "Date e.g. yyyy-MM-dd\r\n\r\nSpecifies the start date for profit and loss report\r\n\r\nIf no parameter is provided, the date of 12 months before the end date will be used."
          schema:
            type: "string"
        - name: "endDate"
          in: "query"
          description: "Date e.g. yyyy-MM-dd\r\n\r\nSpecifies the end date for profit and loss report \r\n\r\nIf no parameter is provided, the current date will be used."
          schema:
            type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfitAndLossResponse"
              example:
                startDate: "2020-07-01"
                endDate: "2021-06-30"
                netProfitLoss: 123
                revenue:
                  total: 20922.46
                  accountTypes:
                    - total: 20825.41
                      title: "Trading Income"
                      accounts:
                        - accountID: "abcdefab-2006-43c2-a5da-3c0e5f43b452"
                          accountType: "REVENUE"
                          code: "200"
                          name: "Sales"
                          reportingCode: "REV"
                          total: 20825.41
                    - total: 97.05
                      title: "Other Income"
                      accounts:
                        - accountID: "abcdefab-4d63-4af8-937f-04087ae2e36e"
                          accountType: "OTHERINCOME"
                          code: "270"
                          name: "Interest Income"
                          reportingCode: "REV.OTH"
                          total: 97.05
                expense:
                  total: 1282.06
                  accountTypes:
                    - total: 1137.59
                      title: "Direct Cost"
                      accounts:
                        - accountID: "abcdefab-d381-4bd6-ba47-7af927d25825"
                          accountType: "DIRECTCOSTS"
                          code: "300"
                          name: "Purchases"
                          reportingCode: "EXP.DC"
                          total: 1137.59
                    - total: 144.47
                      title: "Operating Expenses"
                      accounts:
                        - accountID: "abcdefab-f897-4168-b5d1-2279bf74bb82"
                          accountType: "EXPENSE"
                          code: "453"
                          name: "Office Expenses"
                          reportingCode: "EXP"
                          total: 144.47
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "invalid-request"
                title: "InvalidRequest"
                status: 400
                detail: "Organisation xxx does not exist"
  /FinancialStatements/TrialBalance:
    get:
      security:
        - OAuth2:
            - "finance.statements.read"
      tags:
        - "TrialBalance"
      summary: "Get Trial Balance report"
      description: "The trial balance provides a detailed list of all accounts of an organisation at a point in time, with revenue and expense items being year to date."
      parameters:
        - name: "Xero-Tenant-Id"
          in: "header"
          description: "Xero Organisation Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "Xero-User-Id"
          in: "header"
          description: "Xero User Id"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "endDate"
          in: "query"
          description: "Date e.g. yyyy-MM-dd \r\n\r\nSpecifies the end date for trial balance report \r\n\r\nIf no parameter is provided, the current date will be used."
          schema:
            type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrialBalanceResponse"
              example:
                startDate: "2020-07-01"
                endDate: "2021-06-30"
                accounts:
                  - accountId: "abcdefab-3bbf-4f2a-9e4c-20ec7b8e6b41"
                    accountType: "ASSET"
                    accountCode: "ASS"
                    accountClass: "BANK"
                    status: "ACTIVE"
                    reportingCode: "ASS"
                    accountName: "Everyday transactions"
                    balance:
                      value: 100
                      entryType: "DEBIT"
                    signedBalance: -23
                    accountMovement:
                      debits: 0
                      credits: 0
                      movement:
                        value: 123
                        entryType: "CREDIT"
                      signedMovement: 0
        400:
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
              example:
                type: "invalid-request"
                title: "InvalidRequest"
                status: 400
                detail: "Organisation xxx does not exist"
components:
  securitySchemes:
    OAuth2:
      type: "oauth2"
      description: "For more information visit https://developer.xero.com/documentation/oauth2/overview"
      flows:
        authorizationCode:
          authorizationUrl: "https://login.xero.com/identity/connect/authorize"
          tokenUrl: "https://identity.xero.com/connect/token"
          scopes:
            finance.statements.read: "Grant read-only access to financial statements"
  schemas:
    BalanceSheetAccountDetail:
      type: "object"
      properties:
        code:
          type: "string"
          description: "Accounting code"
          nullable: true
        accountID:
          type: "string"
          description: "ID of the account"
          format: "uuid"
        name:
          type: "string"
          description: "Account name"
          nullable: true
        reportingCode:
          type: "string"
          description: "Reporting code"
          nullable: true
        total:
          type: "number"
          description: "Total movement on this account"
          format: "double"
      additionalProperties: false
    BalanceSheetAccountGroup:
      type: "object"
      properties:
        accountTypes:
          type: "array"
          items:
            $ref: "#/components/schemas/BalanceSheetAccountType"
          nullable: true
        total:
          type: "number"
          description: "Total value of all the accounts in this type"
          format: "double"
      additionalProperties: false
    BalanceSheetAccountType:
      type: "object"
      properties:
        accountType:
          type: "string"
          description: "The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>"
          nullable: true
        accounts:
          type: "array"
          items:
            $ref: "#/components/schemas/BalanceSheetAccountDetail"
          description: "A list of all accounts of this type. Refer to the Account section below for each account element detail."
          nullable: true
        total:
          type: "number"
          description: "Total value of all the accounts in this type"
          format: "double"
      additionalProperties: false
    BalanceSheetResponse:
      type: "object"
      properties:
        balanceDate:
          type: "string"
          description: "Balance date of the report"
          nullable: true
        asset:
          $ref: "#/components/schemas/BalanceSheetAccountGroup"
        liability:
          $ref: "#/components/schemas/BalanceSheetAccountGroup"
        equity:
          $ref: "#/components/schemas/BalanceSheetAccountGroup"
      additionalProperties: false
    CashBalance:
      type: "object"
      properties:
        openingCashBalance:
          type: "number"
          description: "Opening balance of cash and cash equivalents"
          format: "double"
        closingCashBalance:
          type: "number"
          description: "Closing balance of cash and cash equivalents"
          format: "double"
        netCashMovement:
          type: "number"
          description: "Net movement of cash and cash equivalents for the period"
          format: "double"
          readOnly: true
      additionalProperties: false
    CashflowAccount:
      type: "object"
      properties:
        accountId:
          type: "string"
          description: "ID of the account"
          format: "uuid"
        accountType:
          type: "string"
          description: "The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>"
          nullable: true
        accountClass:
          type: "string"
          description: "The class of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountClassTypes'>Account Class Types</a>"
          nullable: true
        code:
          type: "string"
          description: "Account code"
          nullable: true
        name:
          type: "string"
          description: "Account name"
          nullable: true
        reportingCode:
          type: "string"
          description: "Reporting code used for cash flow classification"
          nullable: true
        total:
          type: "number"
          description: "Total amount for the account"
          format: "double"
      additionalProperties: false
    CashflowActivity:
      type: "object"
      properties:
        name:
          type: "string"
          description: "Name of the cashflow activity type. It will be either Operating Activities, Investing Activities or Financing Activities"
          nullable: true
        total:
          type: "number"
          description: "Total value of the activity type"
          format: "double"
        cashflowTypes:
          type: "array"
          items:
            $ref: "#/components/schemas/CashflowType"
          nullable: true
      additionalProperties: false
    CashflowResponse:
      type: "object"
      properties:
        startDate:
          type: "string"
          description: "Start date of the report"
          format: "date-time"
        endDate:
          type: "string"
          description: "End date of the report"
          format: "date-time"
        cashBalance:
          $ref: "#/components/schemas/CashBalance"
        cashflowActivities:
          type: "array"
          items:
            $ref: "#/components/schemas/CashflowActivity"
          description: "Break down of cash and cash equivalents for the period"
          nullable: true
      additionalProperties: false
    CashflowType:
      type: "object"
      properties:
        name:
          type: "string"
          description: "Name of the activity"
          nullable: true
        total:
          type: "number"
          description: "Total value of the activity"
          format: "double"
        accounts:
          type: "array"
          items:
            $ref: "#/components/schemas/CashflowAccount"
          description: "List of the accounts in this activity"
          nullable: true
      additionalProperties: false
    PnlAccount:
      type: "object"
      properties:
        accountID:
          type: "string"
          description: "ID of the account"
          format: "uuid"
        accountType:
          type: "string"
          description: "The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>"
          nullable: true
        code:
          type: "string"
          description: "Account code"
          nullable: true
        name:
          type: "string"
          description: "Account name"
          nullable: true
        reportingCode:
          type: "string"
          description: "Reporting code (Shown if set)"
          nullable: true
        total:
          type: "number"
          description: "Total movement on this account"
          format: "double"
      additionalProperties: false
    PnlAccountClass:
      type: "object"
      properties:
        total:
          type: "number"
          description: "Total revenue/expense value"
          format: "double"
        accountTypes:
          type: "array"
          items:
            $ref: "#/components/schemas/PnlAccountType"
          description: "Contains trading income and other income for revenue section / operating expenses and direct cost for expense section if the data is available for each section. Refer to the account type element below"
          nullable: true
      additionalProperties: false
    PnlAccountType:
      type: "object"
      properties:
        total:
          type: "number"
          description: "Total movement on this account type"
          format: "double"
        title:
          type: "string"
          description: "Name of this account type, it will be either Trading Income or Other Income for Revenue section / Direct Cost or Operating Expenses for Expense section"
          nullable: true
        accounts:
          type: "array"
          items:
            $ref: "#/components/schemas/PnlAccount"
          description: "A list of the movement on each account detail during the query period. Refer to the account detail element below"
          nullable: true
      additionalProperties: false
    Problem:
      type: "object"
      properties:
        type:
          $ref: "#/components/schemas/ProblemType"
        title:
          type: "string"
          nullable: true
        status:
          type: "integer"
          format: "int32"
        detail:
          type: "string"
          nullable: true
      additionalProperties: false
    ProblemType:
      enum:
        - "NotSet"
        - "invalid-request"
        - "invalid-application"
        - "request-too-large"
        - "service-unavailable"
        - "internal-error"
      type: "string"
    ProfitAndLossResponse:
      type: "object"
      properties:
        startDate:
          type: "string"
          description: "Start date of the report"
          format: "date-time"
        endDate:
          type: "string"
          description: "End date of the report"
          format: "date-time"
        netProfitLoss:
          type: "number"
          description: "Net profit loss value"
          format: "double"
        revenue:
          $ref: "#/components/schemas/PnlAccountClass"
        expense:
          $ref: "#/components/schemas/PnlAccountClass"
      additionalProperties: false
    TrialBalanceAccount:
      type: "object"
      properties:
        accountId:
          type: "string"
          description: "ID of the account"
          format: "uuid"
        accountType:
          type: "string"
          description: "The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>"
          nullable: true
        accountCode:
          type: "string"
          description: "Customer defined alpha numeric account code e.g 200 or SALES"
          nullable: true
        accountClass:
          type: "string"
          description: "The class of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountClassTypes'>Account Class Types</a>"
          nullable: true
        status:
          type: "string"
          description: "Accounts with a status of ACTIVE can be updated to ARCHIVED. See <a href='https://developer.xero.com/documentation/api/types#AccountStatusCodes'>Account Status Codes</a>"
          nullable: true
        reportingCode:
          type: "string"
          description: "Reporting code (Shown if set)"
          nullable: true
        accountName:
          type: "string"
          description: "Name of the account"
          nullable: true
        balance:
          $ref: "#/components/schemas/TrialBalanceEntry"
        signedBalance:
          type: "number"
          description: "Value of balance. Expense and Asset accounts code debits as positive. Revenue, Liability, and Equity accounts code debits as negative"
          format: "double"
        accountMovement:
          $ref: "#/components/schemas/TrialBalanceMovement"
      additionalProperties: false
    TrialBalanceEntry:
      type: "object"
      properties:
        value:
          type: "number"
          description: "Net movement or net balance in the account"
          format: "double"
        entryType:
          type: "string"
          description: "Sign (Debit/Credit) of the movement of balance in the account"
          nullable: true
      additionalProperties: false
    TrialBalanceMovement:
      type: "object"
      properties:
        debits:
          type: "number"
          description: "Debit amount"
          format: "double"
        credits:
          type: "number"
          description: "Credit amount"
          format: "double"
        movement:
          $ref: "#/components/schemas/TrialBalanceEntry"
        signedMovement:
          type: "number"
          description: "Value of movement. Expense and Asset accounts code debits as positive. Revenue, Liability, and Equity accounts code debits as negative"
          format: "double"
      additionalProperties: false
    TrialBalanceResponse:
      type: "object"
      properties:
        startDate:
          type: "string"
          description: "Start date of the report"
          nullable: true
        endDate:
          type: "string"
          description: "End date of the report"
          nullable: true
        accounts:
          type: "array"
          items:
            $ref: "#/components/schemas/TrialBalanceAccount"
          description: "Refer to the accounts section below"
          nullable: true
      additionalProperties: false
